### ISSUE TITLE
page width not reactive

### ISSUE THREAD

**Issue by rupraph** [rupraph/pipo-modules-FW#39]
When tested on a phone the width of the page does not scale so that the config fits the page.

**Comment by Leo-Nicolle** [comment]
Yes there were margins and paddings everywhere, I fixed it [in this one](https://github.com/rupraph/pipo-single/pull/35)

**Comment by rupraph** [comment]
> Yes there were margins and paddings everywhere, I fixed it [in this one](https://github.com/rupraph/pipo-single/pull/35)

Sorry, my bad !

**Comment by Leo-Nicolle** [comment]
Hehe I knew you were involved in the massacre of my beautiful CSS :).

Try it again on `develop` or `sensors-value-socket`, I think we can close the issue.
