### ISSUE TITLE
make slider ticks smaller

### ISSUE THREAD

**Issue by rupraph** [rupraph/pipo-modules-FW#55]
currently it seems slider to select sensor range moves from int to int.
We need to be able to have 1 decimal

**Comment by Leo-Nicolle** [comment]
I need your input: 
 - motion angles: [-180;180] or [-90;90] => step is `1`
 - motion acceleration: What is the range ? What is the step
 - analog volt inputs: [0-5], =>step is `0.1`
 - analog touch input: What is the range ? What is the step?
 - range: [0;120] mm right? step is `1`?

**Comment by rupraph** [comment]
Actually I updated the schema.ts yesterday in a comit.
You should find some ranges there.

acceleration is -16/+16 g , step 0.5 or 0.1
For touch range is 0- 200000 step 1
range 0-5000 -> mm, step 1

Actually I am not sure how much effort we should put in such step discrimination. My concern was simply the steps were not small enough for volatage.

**Comment by Leo-Nicolle** [comment]
It is super easy
I just needed the right values. I'll try to have a log step for range, you might want super precise value on the lower end and less precide on the higher
